Template.postSubmit.events(
  'submit form': (e)->
    e.preventDefault();
    post =
      url: $(e.target).find('[name=url]').val()
      title: $(e.target).find('[name=title]').val()


    errors = validatePost(post)
    if errors.title or errors.url
      return Session.set("postSubmitErrors",errors)

    Meteor.call "postInsert",post,(error,result)->
      if error
        return throwError(error.reason)

      if result.postExists
        throwError("Este Link ya Existe")
      Router.go "postPage", _id:result._id
      return
    return
)

Template.postSubmit.created = ->
  Session.set 'postSubmitErrors', {}
  return

Template.postSubmit.helpers
  errorMessage: (field) ->
    Session.get('postSubmitErrors')[field]
  errorClass: (field) ->
    if !!Session.get('postSubmitErrors')[field] then 'has-error' else ''

# ---
# generated by js2coffee 2.0.1